

name: PikaOS KDE kinetic

on:
  workflow_dispatch

jobs:
  build:
    runs-on: self-hosted
    container:
      image: ubuntu:latest
      volumes:
        - /proc:/proc
      options: --privileged -it

    steps:
    - uses: actions/checkout@v3

    - name: Install needed packages
      run: apt update && apt install debootstrap -y

    - name: Build ISO
      run: ./build.sh

    - uses: actions/upload-artifact@v3
      with:
        name: PikaOS KDE 22.10
        path: builds/
