

name: PikaOS KDE lunar

on:
  workflow_dispatch

jobs:
  build:
    runs-on: self-hosted
    container:
      image: ubuntu:latest
      volumes:
        - /proc:/proc
      options: --privileged -it

    steps:
    - uses: actions/checkout@v3

    - name: Install needed packages
      run: apt update && apt install debootstrap gpg gpg-agent lz4 rsync schedtool wget zstd tar reprepro dpkg-sig -y

    - name: Import GPG key
      id: import_gpg
      uses: crazy-max/ghaction-import-gpg@v5
      with:
        gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
        passphrase: ${{ secrets.PASSPHRASE }}

    - name: Install SSH key
      uses: shimataro/ssh-key-action@v2
      with:
        key: ${{ secrets.SSH_KEY }}
        name: id_rsa
        known_hosts: ${{ secrets.KNOWN_HOSTS }}
        if_key_exists: replace

    - name: Build ISO
      run: ./build.sh
